### ISSUE TITLE
MELPA? :)

### ISSUE THREAD

**Issue by Silex** [Fuco1/ETable#4]
Hey,

What do you think about it? I'll need etable as a dependency somewhat soonish and putting ETable in MELPA would simplify that.

**Comment by Fuco1** [comment]
I don't like melpa much.

melpa stable is kind of acceptable.  Feel free to add a tag for that.

**Comment by Silex** [comment]
Alright... but how can I add a tag? I don't think I can make PR with tags...

**Comment by Fuco1** [comment]
I gave you push rights, no?  (I don't remember)
-- 
Best regards,
  Matúš Goljer

**Comment by Silex** [comment]
Not on this repo no, on dired-hacks yes.

```
128 git … push -v --set-upstream origin test:refs/heads/test
Pushing to git@github.com:Fuco1/ETable.git
ERROR: Permission to Fuco1/ETable.git denied to Silex.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Silex** [comment]
@Fuco1: ping

**Comment by Silex** [comment]
@Fuco1: given I'm stuck here I'll make a PR for MELPA anyway, you're free to add a tag if you want it automatically added to MELPA-stable.
